global:
  scrape_interval: 10s
  scrape_timeout: 10s

rule_files:
- /etc/prometheus/rules.yml

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets:
      - prometheus:9090
  - job_name: dev-slave-db-exporter
    static_configs:
    - targets:
      - 45.82.139.39:9101
  - job_name: dev-master-db-exporter
    static_configs:
    - targets:
      - 45.82.139.39:9102
  - job_name: core-slave-db-exporter
    static_configs:
    - targets:
      - 37.32.10.32:9101
  - job_name: core-master-db-exporter
    static_configs:
    - targets:
      - 37.32.10.32:9102